services:
  api:
    build: 
      context: .
      dockerfile: dockerfile
    image: marketspace-api:v1
    container_name: marketspace-api
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: marketspace-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db_scripts/create.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
volumes:
  db-data:
    